### ISSUE TITLE
Handle reconnect when Redis connection is lost

### ISSUE THREAD

**Issue by PuKoren** [dial-once/node-cache-manager-redis#30] opened 2016-07-26 16:09 UTC

**Comment by jkernech** [comment] 2016-07-30 12:20
Should be related to #5

**Comment by mrister** [comment] 2016-08-01 12:34
After a conversation on slack and testing we saw that redis does get reconnected on default settings and that the possible bottleneck could be `sol-redis-pool` module that restricts some redis options being passed into it.  One example https://github.com/joshuah/sol-redis-pool/pull/17

So @jkernech @PuKoren  Any ideas on how to proceed (or close this issue) ?

**Comment by PuKoren** [comment] 2016-08-01 12:53
@mrister can you describe the test processed?

What do you mean by bottleneck on `sol-redis-pool`? The underlying redis is reconnected by sol-redis-pool acts if it was still disconnected?

**Comment by mrister** [comment] 2016-08-01 12:58
@PuKoren  Sure:
For sol redis poll it does not pass options to redis (like the PR i sent) which control reconnect and retry strategies

Test was:
- Start a redis cache via redis-node-cache-manager
- Do some sets and gets of a same key to make sure it is working
- Disable redis
- Do some sets and gets
- Restart redis
- Do gets and sets to make sure it is working.

Reconnect happened as well as operations got queued while server was down.

**Comment by PuKoren** [comment] 2016-08-01 13:00
Well if it is working as expected you can close the issue

**Comment by mrister** [comment] 2016-08-01 13:01
@jkernech You did some investigations also, what do you think, ok to close ?

**Comment by jkernech** [comment] 2016-08-01 13:12
@mrister Ok to close, I couldn't reproduce the issue

**Comment by mrister** [comment] 2016-08-01 13:16
Closing as discussed.

**Closed by mrister** 2016-08-01 13:16 UTC
Labels: in progress
